# Generated by Django 4.2.2 on 2023-06-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imge', models.ImageField(upload_to='pics')),
                ('name', models.CharField(max_length=240)),
                ('desc', models.TextField()),
            ],
        ),
    ]
